var testScene = {
    name: "Scene 1",
    Backgrounds: [
        {
            height: 420, width: 840, positionX: 0, positionY: 0,
            Draw: function(d) {
                d.drawImage(document.getElementById("background-scene1"), 0, 0);
            }
        }
    ],
	Objects: [new ObjectTest(), new ObjectTestNoOffset(), new ObjectFireBall({x:50, y:300, speed:0.01, angle:0, size:12})],
    Foregrounds: [],
    Terrain: [
        [ "Bricks", "Bricks", "Bricks", "Bricks"],
        [ "Bricks", "Bricks", "Bricks", "Bricks"],
        [ "Bricks", "Bricks", "Bricks", "Bricks"],
        [ "Bricks", "Bricks", "Bricks", "Bricks"],
        [ "Bricks", "Bricks", "Bricks", "Bricks"],
        [ "Bricks", "Bricks", "Bricks", "Bricks"],
        [ "Bricks", "Bricks", "Bricks", "Bricks"],
        [ "Bricks", "Bricks", "Bricks", "Bricks"],
        [ "Bricks", "Bricks", "Bricks", "Bricks"],
        [ "Bricks", "Bricks", "Bricks", "Bricks", "Bricks"],
        [ "Bricks", "Bricks", "Bricks", "Bricks"],
        [ "Bricks", "Bricks", "Bricks", "Bricks"],
        [ "Bricks", "Bricks", "Bricks", "Bricks"],
        [ "Bricks", "Bricks", "Bricks", "Bricks"],
        [ "Bricks", "Bricks", "Bricks", "Bricks"],
        [ "Bricks", "Bricks", "Bricks", "Bricks"],
        [ "Bricks", "Bricks", "Bricks", "Bricks"],
        [ "Bricks", "Bricks", "Bricks", "Bricks"],
        [ "Bricks", "Bricks", "Bricks", "Bricks"],
        [ "Bricks", "Bricks", "Bricks", "Bricks"],
        [ "Bricks", "Bricks", "Bricks", "Bricks"],
        [ "Bricks", "Bricks", "Bricks", "Bricks", "Empty", "Empty", "Red"],
        [ "Bricks", "Bricks", "Bricks", "Bricks", "Empty", "Empty", "Red"],
        [ "Bricks", "Bricks", "Bricks", "Bricks", "Empty", "Empty", "Red"],
        [ "Bricks", "Bricks", "Bricks", "Bricks"],
        [ "Bricks", "Bricks", "Bricks", "Bricks"],
        [ "Bricks", "Bricks", "Bricks", "Bricks", "Empty", "Empty", "Empty", "Empty", "Red"],
        [ "Bricks", "Bricks", "Bricks", "Bricks", "Empty", "Empty", "Empty", "Empty", "Red"],
        [ "Bricks", "Bricks", "Bricks", "Bricks", "Empty", "Empty", "Empty", "Empty", "Red"],
        [ "Bricks", "Bricks", "Bricks", "Bricks"],
        [ "Bricks", "Bricks", "Bricks", "Bricks"],
        [ "Bricks", "Bricks", "Bricks", "Bricks", "Empty", "Empty", "Red"],
        [ "Bricks", "Bricks", "Bricks", "Bricks", "Empty", "Empty", "Red"],
        [ "Bricks", "Bricks", "Bricks", "Bricks", "Empty", "Empty", "Red"],
        [ "Bricks", "Bricks", "Bricks", "Bricks"],
        [ "Bricks", "Bricks", "Bricks", "Bricks"],
        [ "Bricks", "Bricks", "Bricks", "Bricks", "Bricks"],
        [ "Bricks", "Bricks", "Bricks", "Bricks"],
        [ "Bricks", "Bricks", "Bricks", "Bricks"],
        [ "Bricks", "Bricks", "Bricks", "Bricks"],
        [ "Bricks", "Bricks", "Bricks", "Bricks"],
        [ "Bricks", "Bricks", "Bricks", "Bricks"],
        [ "Bricks", "Bricks", "Bricks", "Bricks"],
        [ "Bricks", "Bricks", "Bricks", "Bricks"],
        [ "Bricks", "Bricks", "Bricks", "Bricks"],
        [ "Bricks", "Bricks", "Bricks", "Bricks"],
        [ "Bricks", "Bricks", "Bricks", "Bricks"],
        [ "Bricks", "Bricks", "Bricks", "Bricks"],
        [ "Bricks", "Bricks", "Bricks", "Bricks"],
        [ "Bricks", "Bricks", "Bricks", "Bricks"],
        [ "Bricks", "Bricks", "Bricks", "Bricks"],
        [ "Bricks", "Bricks", "Bricks", "Bricks"],
        [ "Bricks", "Bricks", "Bricks", "Bricks"],
        [ "Bricks", "Bricks", "Bricks", "Bricks"],
        [ "Bricks", "Bricks", "Bricks", "Bricks"],
        [ "Bricks", "Bricks", "Bricks", "Bricks"],
        [ "Bricks", "Bricks", "Bricks", "Bricks"],
        [ "Bricks", "Bricks", "Bricks", "Bricks"],
        [ "Bricks", "Bricks", "Bricks", "Bricks"],
        [ "Bricks", "Bricks", "Bricks", "Bricks"],
        [ "Bricks", "Bricks", "Bricks", "Bricks"],
        [ "Bricks", "Bricks", "Bricks", "Bricks"],
        [ "Bricks", "Bricks", "Bricks", "Bricks"],
        [ "Bricks", "Bricks", "Bricks", "Bricks"],
        [ "Bricks", "Bricks", "Bricks", "Bricks"],
        [ "Bricks", "Bricks", "Bricks", "Bricks"],
        [ "Bricks", "Bricks", "Bricks", "Bricks"],
        [ "Bricks", "Bricks", "Bricks", "Bricks"],
        [ "Bricks", "Bricks", "Bricks", "Bricks"],
        [ "Bricks", "Bricks", "Bricks", "Bricks"],
        [ "Bricks", "Bricks", "Bricks", "Bricks"],
        [ "Bricks", "Bricks", "Bricks", "Bricks"],
        [ "Bricks", "Bricks", "Bricks", "Bricks"],
        [ "Bricks", "Bricks", "Bricks", "Bricks"],
        [ "Bricks", "Bricks", "Bricks", "Bricks"],
        [ "Bricks", "Bricks", "Bricks", "Bricks"],
        [ "Bricks", "Bricks", "Bricks", "Bricks"],
        [ "Bricks", "Bricks", "Bricks", "Bricks"],
        [ "Bricks", "Bricks", "Bricks", "Bricks"],
        [ "Bricks", "Bricks", "Bricks", "Bricks"],
        [ "Bricks", "Bricks", "Bricks", "Bricks"],
        [ "Bricks", "Bricks", "Bricks", "Bricks"],
        [ "Bricks", "Bricks", "Bricks", "Bricks"],
        [ "Bricks", "Bricks", "Bricks", "Bricks"],
        [ "Bricks", "Bricks", "Bricks", "Bricks"],
        [ "Bricks", "Bricks", "Bricks", "Bricks"],
        [ "Bricks", "Bricks", "Bricks", "Bricks"],
        [ "Bricks", "Bricks", "Bricks", "Bricks"],
        [ "Bricks", "Bricks", "Bricks", "Bricks"],
        [ "Bricks", "Bricks", "Bricks", "Bricks"],
        [ "Bricks", "Bricks", "Bricks", "Bricks"],
        [ "Bricks", "Bricks", "Bricks", "Bricks"],
        [ "Bricks", "Bricks", "Bricks", "Bricks"],
        [ "Bricks", "Bricks", "Bricks", "Bricks"],
        [ "Bricks", "Bricks", "Bricks", "Bricks"],
        [ "Bricks", "Bricks", "Bricks", "Bricks"],
        [ "Bricks", "Bricks", "Bricks", "Bricks"],
        [ "Bricks", "Bricks", "Bricks", "Bricks"],
        [ "Bricks", "Bricks", "Bricks", "Bricks"],
        [ "Bricks", "Bricks", "Bricks", "Bricks"],
        [ "Bricks", "Bricks", "Bricks", "Bricks"],
        [ "Bricks", "Bricks", "Bricks", "Bricks"],
        [ "Bricks", "Bricks", "Bricks", "Bricks"],
        [ "Bricks", "Bricks", "Bricks", "Bricks"],
        [ "Bricks", "Bricks", "Bricks", "Bricks"],
        [ "Bricks", "Bricks", "Bricks", "Bricks"],
        [ "Bricks", "Bricks", "Bricks", "Bricks"],
        [ "Bricks", "Bricks", "Bricks", "Bricks"],
        [ "Bricks", "Bricks", "Bricks", "Bricks"]
    ]
}