var testScene = {
    name: "Scene 1",
    Backgrounds: [
        function(d) {
            d.drawImage(document.getElementById("background-scene1"), 0, 0);
        }
    ],
	Objects: [new ObjectTest()],
    Foregrounds: [],
    Terrain: [
        [ "Bricks", "Bricks", "Bricks", "Bricks"],
        [ "Bricks", "Bricks", "Bricks", "Bricks"],
        [ "Bricks", "Bricks", "Bricks", "Bricks"],
        [ "Bricks", "Bricks", "Bricks", "Bricks"],
        [ "Bricks", "Bricks", "Bricks", "Bricks"],
        [ "Bricks", "Bricks", "Bricks", "Bricks"],
        [ "Bricks", "Bricks", "Bricks", "Bricks"],
        [ "Bricks", "Bricks", "Bricks", "Bricks"],
        [ "Bricks", "Bricks", "Bricks", "Bricks"],
        [ "Bricks", "Bricks", "Bricks", "Bricks", "Bricks"],
        [ "Bricks", "Bricks", "Bricks", "Bricks"],
        [ "Bricks", "Bricks", "Bricks", "Bricks"],
        [ "Bricks", "Bricks", "Bricks", "Bricks"],
        [ "Bricks", "Bricks", "Bricks", "Bricks"],
        [ "Bricks", "Bricks", "Bricks", "Bricks"],
        [ "Bricks", "Bricks", "Bricks", "Bricks"],
        [ "Bricks", "Bricks", "Bricks", "Bricks"],
        [ "Bricks", "Bricks", "Bricks", "Bricks"],
        [ "Bricks", "Bricks", "Bricks", "Bricks"],
        [ "Bricks", "Bricks", "Bricks", "Bricks"],
        [ "Bricks", "Bricks", "Bricks", "Bricks"],
        [ "Bricks", "Bricks", "Bricks", "Bricks", "Empty", "Empty", "Red"],
        [ "Bricks", "Bricks", "Bricks", "Bricks", "Empty", "Empty", "Red"],
        [ "Bricks", "Bricks", "Bricks", "Bricks", "Empty", "Empty", "Red"],
        [ "Bricks", "Bricks", "Bricks", "Bricks"],
        [ "Bricks", "Bricks", "Bricks", "Bricks"],
        [ "Bricks", "Bricks", "Bricks", "Bricks", "Empty", "Empty", "Empty", "Empty", "Red"],
        [ "Bricks", "Bricks", "Bricks", "Bricks", "Empty", "Empty", "Empty", "Empty", "Red"],
        [ "Bricks", "Bricks", "Bricks", "Bricks", "Empty", "Empty", "Empty", "Empty", "Red"],
        [ "Bricks", "Bricks", "Bricks", "Bricks"],
        [ "Bricks", "Bricks", "Bricks", "Bricks"],
        [ "Bricks", "Bricks", "Bricks", "Bricks", "Empty", "Empty", "Red"],
        [ "Bricks", "Bricks", "Bricks", "Bricks", "Empty", "Empty", "Red"],
        [ "Bricks", "Bricks", "Bricks", "Bricks", "Empty", "Empty", "Red"],
        [ "Bricks", "Bricks", "Bricks", "Bricks"],
        [ "Bricks", "Bricks", "Bricks", "Bricks"],
        [ "Bricks", "Bricks", "Bricks", "Bricks", "Bricks"],
        [ "Bricks", "Bricks", "Bricks", "Bricks"],
        [ "Bricks", "Bricks", "Bricks", "Bricks"],
        [ "Bricks", "Bricks", "Bricks", "Bricks"],
        [ "Bricks", "Bricks", "Bricks", "Bricks"],
        [ "Bricks", "Bricks", "Bricks", "Bricks"],
        [ "Bricks", "Bricks", "Bricks", "Bricks"],
        [ "Bricks", "Bricks", "Bricks", "Bricks"],
        [ "Bricks", "Bricks", "Bricks", "Bricks"],
        [ "Bricks", "Bricks", "Bricks", "Bricks"],
        [ "Bricks", "Bricks", "Bricks", "Bricks"],
        [ "Bricks", "Bricks", "Bricks", "Bricks"],
        [ "Bricks", "Bricks", "Bricks", "Bricks"],
        [ "Bricks", "Bricks", "Bricks", "Bricks"],
        [ "Bricks", "Bricks", "Bricks", "Bricks"],
        [ "Bricks", "Bricks", "Bricks", "Bricks"],
        [ "Bricks", "Bricks", "Bricks", "Bricks"],
        [ "Bricks", "Bricks", "Bricks", "Bricks"],
        [ "Bricks", "Bricks", "Bricks", "Bricks"],
        [ "Bricks", "Bricks", "Bricks", "Bricks"],
        [ "Bricks", "Bricks", "Bricks", "Bricks"],
        [ "Bricks", "Bricks", "Bricks", "Bricks"],
        [ "Bricks", "Bricks", "Bricks", "Bricks"],
        [ "Bricks", "Bricks", "Bricks", "Bricks"],
        [ "Bricks", "Bricks", "Bricks", "Bricks"],
        [ "Bricks", "Bricks", "Bricks", "Bricks"],
        [ "Bricks", "Bricks", "Bricks", "Bricks"],
        [ "Bricks", "Bricks", "Bricks", "Bricks"],
        [ "Bricks", "Bricks", "Bricks", "Bricks"],
        [ "Bricks", "Bricks", "Bricks", "Bricks"],
        [ "Bricks", "Bricks", "Bricks", "Bricks"],
        [ "Bricks", "Bricks", "Bricks", "Bricks"],
        [ "Bricks", "Bricks", "Bricks", "Bricks"],
        [ "Bricks", "Bricks", "Bricks", "Bricks"],
        [ "Bricks", "Bricks", "Bricks", "Bricks"],
        [ "Bricks", "Bricks", "Bricks", "Bricks"],
        [ "Bricks", "Bricks", "Bricks", "Bricks"],
        [ "Bricks", "Bricks", "Bricks", "Bricks"],
        [ "Bricks", "Bricks", "Bricks", "Bricks"],
        [ "Bricks", "Bricks", "Bricks", "Bricks"],
        [ "Bricks", "Bricks", "Bricks", "Bricks"],
        [ "Bricks", "Bricks", "Bricks", "Bricks"],
        [ "Bricks", "Bricks", "Bricks", "Bricks"],
        [ "Bricks", "Bricks", "Bricks", "Bricks"],
        [ "Bricks", "Bricks", "Bricks", "Bricks"],
        [ "Bricks", "Bricks", "Bricks", "Bricks"],
        [ "Bricks", "Bricks", "Bricks", "Bricks"],
        [ "Bricks", "Bricks", "Bricks", "Bricks"],
        [ "Bricks", "Bricks", "Bricks", "Bricks"],
        [ "Bricks", "Bricks", "Bricks", "Bricks"],
        [ "Bricks", "Bricks", "Bricks", "Bricks"],
        [ "Bricks", "Bricks", "Bricks", "Bricks"],
        [ "Bricks", "Bricks", "Bricks", "Bricks"],
        [ "Bricks", "Bricks", "Bricks", "Bricks"],
        [ "Bricks", "Bricks", "Bricks", "Bricks"],
        [ "Bricks", "Bricks", "Bricks", "Bricks"],
        [ "Bricks", "Bricks", "Bricks", "Bricks"],
        [ "Bricks", "Bricks", "Bricks", "Bricks"],
        [ "Bricks", "Bricks", "Bricks", "Bricks"],
        [ "Bricks", "Bricks", "Bricks", "Bricks"],
        [ "Bricks", "Bricks", "Bricks", "Bricks"],
        [ "Bricks", "Bricks", "Bricks", "Bricks"],
        [ "Bricks", "Bricks", "Bricks", "Bricks"],
        [ "Bricks", "Bricks", "Bricks", "Bricks"],
        [ "Bricks", "Bricks", "Bricks", "Bricks"],
        [ "Bricks", "Bricks", "Bricks", "Bricks"],
        [ "Bricks", "Bricks", "Bricks", "Bricks"],
        [ "Bricks", "Bricks", "Bricks", "Bricks"],
        [ "Bricks", "Bricks", "Bricks", "Bricks"],
        [ "Bricks", "Bricks", "Bricks", "Bricks"],
        [ "Bricks", "Bricks", "Bricks", "Bricks"],
        [ "Bricks", "Bricks", "Bricks", "Bricks"],
        [ "Bricks", "Bricks", "Bricks", "Bricks"]
    ]
}