var testWorld = { //World
    name: "Test World",
    Scenes: [ //Scenes
        { //Scene 1
            name: "Scene 1",
            farBackground: null,
            normalBackground: "background-scene1",
            foreground: null,
            Terrain: [
                [ "Test", "TestB", "TestB", "TestA", "TestA" ],
                [ "TestA", "TestA", "TestA" ],
                [ "TestA", "TestA", "TestB"],
                [ "Test", "Test", "TestB", "TestA"],
                [ "Test", "TestB", "TestB", "TestA", "TestA" ],
                [ "TestA", "TestA", "TestA" ],
                [ "TestA", "TestA", "TestB"],
                [ "Test", "Test", "TestB", "TestA"],
                [ "Test", "TestB", "TestB", "TestA", "TestA" ],
                [ "TestA", "TestA", "TestA" ],
                [ "TestA", "TestA", "TestB"],
                [ "Test", "Test", "TestB", "TestA"],
                [ "Test", "TestB", "TestB", "TestA", "TestA" ],
                [ "TestA", "TestA", "TestA" ],
                [ "TestA", "TestA", "TestB"],
                [ "Test", "Test", "TestB", "TestA"],
                [ "Test", "TestB", "TestB", "TestA", "TestA" ],
                [ "TestA", "TestA", "TestA" ],
                [ "TestA", "TestA", "TestB"],
                [ "Test", "Test", "TestB", "TestA"],
                [ "Test", "TestB", "TestB", "TestA", "TestA" ],
                [ "TestA", "TestA", "TestA" ],
                [ "TestA", "TestA", "TestB"],
                [ "Test", "Test", "TestB", "TestA"],
                [ "Test", "TestB", "TestB", "TestA", "TestA" ],
                [ "TestA", "TestA", "TestA" ],
                [ "TestA", "TestA", "TestB"],
                [ "Test", "Test", "TestB", "TestA"]
            ]
        },
        {//Scene 2
            name: "Awesome Battle",
            normalBackground: "background-scene2",
            Terrain: [
                [ "Test", "TestB", "TestB", "TestA", "TestA" ],
                [ "TestA", "TestA", "TestA" ],
                [ "TestA", "TestA", "TestB"],
                [ "Test", "Test", "TestB", "TestA"],
                [ "Test", "TestB", "TestB", "TestA", "TestA" ],
                [ "TestA", "TestA", "TestA" ],
                [ "TestA", "TestA", "TestB"],
                [ "Test", "Test", "TestB", "TestA"],
                [ "Test", "TestB", "TestB", "TestA", "TestA" ],
                [ "TestA", "TestA", "TestA" ],
                [ "TestA", "TestA", "TestB"],
                [ "Test", "Test", "TestB", "TestA"],
                [ "Test", "TestB", "TestB", "TestA", "TestA" ],
                [ "TestA", "TestA", "TestA" ],
                [ "TestA", "TestA", "TestB"],
                [ "Test", "Test", "TestB", "TestA"],
                [ "Test", "TestB", "TestB", "TestA", "TestA" ],
                [ "TestA", "TestA", "TestA" ],
                [ "TestA", "TestA", "TestB"],
                [ "Test", "Test", "TestB", "TestA"],
                [ "Test", "TestB", "TestB", "TestA", "TestA" ],
                [ "TestA", "TestA", "TestA" ],
                [ "TestA", "TestA", "TestB"],
                [ "Test", "Test", "TestB", "TestA"],
                [ "Test", "TestB", "TestB", "TestA", "TestA" ],
                [ "TestA", "TestA", "TestA" ],
                [ "TestA", "TestA", "TestB"],
                [ "Test", "Test", "TestB", "TestA"]
            ]
        }
    ]
}